/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import buzz.Configurations;
import buzz.Player;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 * Class for bet round GUI. Inherits components that used from other round type
 * games. This class implements logic of bet round. JOption Pane used to set bet score
 * that a player choose
 * 
 * @author alouvoul
 */
public class betGUI extends generalGUIOptions{
    private static final int IFW = JComponent.WHEN_IN_FOCUSED_WINDOW;
    /**
     * Variable to get bet score that the current player bets.
     */
    private int bet;
    /**
     * number of iterations in a round
     */
    Player tempPlayer;
    
    /**
     * Creates new form betGUI
     */
    public betGUI(categoryChooseGUI cc) {
        super();
        previous = cc;
        iterations = 0;
        initComponents();
        name1.setText(game.getPlayers().get(0).GetName()+": "+game.getPlayers().get(0).GetScore());
        if(game.getPlayers().size()>1){
            name2.setEnabled(true);
            name2.setVisible(true);
            name2.setText(game.getPlayers().get(1).GetName()+": "+game.getPlayers().get(1).GetScore());
        }
        iteration();
        this.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == Configurations.p1a1 && game.getPlayers().size()==1){
            update(answerButton1.getText(),PLAYER1);
        }
        else if(evt.getKeyCode() == Configurations.p1a2 && game.getPlayers().size()==1){
            update(answerButton2.getText(),PLAYER1);
        }
        else if(evt.getKeyCode() == Configurations.p1a3 && game.getPlayers().size()==1){
            update(answerButton3.getText(),PLAYER1);
        }
        else if(evt.getKeyCode() == Configurations.p1a4 && game.getPlayers().size()==1){
            update(answerButton4.getText(),PLAYER1);
        }        
        
        if(evt.getKeyCode() == Configurations.p1a1 ){
            update(answerButton1.getText(),PLAYER1);
            iteration();
        }
        else if(evt.getKeyCode() == Configurations.p2a1 && game.getPlayers().size()>1){
            update(answerButton1.getText(),PLAYER2);
            iteration();
        }
        if(evt.getKeyCode() == Configurations.p1a2){
            update(answerButton2.getText(), PLAYER1);
            iteration();
        }
        else if(evt.getKeyCode() == Configurations.p2a2 && game.getPlayers().size()>1){
            update(answerButton2.getText(),PLAYER2);
            iteration();
        }
        if(evt.getKeyCode() == Configurations.p1a3){
            update(answerButton3.getText(),PLAYER1);
            iteration();
        }
        else if(evt.getKeyCode() == Configurations.p2a3 && game.getPlayers().size()>1){
            update(answerButton3.getText(),PLAYER2);
            iteration();
        }
        if(evt.getKeyCode() == Configurations.p1a4){
            update(answerButton4.getText(),PLAYER1);
            iteration();
        }
        else if(evt.getKeyCode() == Configurations.p2a4 && game.getPlayers().size()>1){
            update(answerButton4.getText(),PLAYER2);
            iteration();
        }
        //iteration();
    }//GEN-LAST:event_formKeyPressed

    /**
     * Check for iteration limit for rounds. Refresh the questions by calling setQuestions
     * method. if limit reached enable previous frame (categoryChoose object).
     * Also calls method to set bet score of a player.
     */
    protected void iteration(){
        
        if(iterations<buzz.Configurations.QUESTIONS_PER_ROUNDS){
            setCurrentPlayer();
            bet = bettingMethod();
            setQuestions();
        }
        else{
            previous.setEnabled(true);
            previous.setVisible(true);
            this.dispose();
        }
        iterations++;
    }
    
    /**
     * Checks if answer is correct and call method to calculate points to add. 
     * Update scores for players if both of them answer and call iteration mathod
     * to change questions.
     * 
     * @param answer Player's answer to check if this is correct.
     * @param i Player number 0 or 1 for 2 players
     */
    private void update(String answer, int player){
        game.playerAnswer(answer, tempPlayer , bet);
        ArrayList<Player> pl = game.getPlayers();
        name1.setText(pl.get(0).GetName()+": "+pl.get(0).GetScore());
        if(pl.size()==2){
            name2.setText(pl.get(1).GetName()+": "+pl.get(1).GetScore());
        }
    }
    
    /**
     * Method to set bet score of a player every round. There are only 4 choices
     * for the player to set.
     * @return Choosen bet score
     */
    private int bettingMethod() {
        Object[] possibilities = {"250", "500", "750","1000"};
        this.setVisible(false);
        while(true){
            String s = (String)JOptionPane.showInputDialog(this,tempPlayer.GetName()+Configurations.betMessage,
                        "Customized Dialog",
                        JOptionPane.PLAIN_MESSAGE,
                        null,
                        possibilities,
                        "ham");
            this.setVisible(true);
            //If a string was returned, say so.
            if ((s != null) && (s.length() > 0)) {
                int bet = Integer.parseInt(s);
                return bet;
            }
        }
    }
    
    /**
     * Method to set current player in rounds. This needs because every question
     * another player bets and answer the question.
     */
    private void setCurrentPlayer() {
        tempPlayer = game.getPlayers().get(iterations%game.getPlayers().size());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
