/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.MainGUI.game;
import java.awt.event.KeyEvent;

/**
 *
 * @author alouvoul
 */
public class fastAnswerGUI extends generalGUIOptions{
    int i = 0;
    
    /**
     * Creates new form fastAnswerGUI
     * @param previous
     */
    public fastAnswerGUI(categoryChooseGUI previous) {
        super();
        this.previous = previous;
        initComponents();
        if(game.getPlayers().size()>1){
            name2.setEnabled(true);
            name2.setVisible(true);
        }
        answered[0] = false;
        answered[1] = false;
        this.setFocusable(true);
        name1.setText(game.getPlayers().get(0).GetName()+": "+game.getPlayers().get(0).GetScore());
        if(game.getPlayers().size()>1){
            name2.setEnabled(true);
            name2.setVisible(true);
            name2.setText(game.getPlayers().get(1).GetName()+": "+game.getPlayers().get(1).GetScore());
        }
        iteration();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_1 && !answered[0]){
            updateUI(answerButton1.getText(),0);
        }
        else if(evt.getKeyCode() == KeyEvent.VK_NUMPAD1 && !answered[1]){
            updateUI(answerButton1.getText(),1);
        }
        if(evt.getKeyCode() == KeyEvent.VK_2 && !answered[0]){
            updateUI(answerButton2.getText(),0);
        }
        else if(evt.getKeyCode() == KeyEvent.VK_NUMPAD2 && !answered[1]){
            updateUI(answerButton2.getText(),1);
        }
        if(evt.getKeyCode() == KeyEvent.VK_3 && !answered[0]){
            updateUI(answerButton3.getText(),0);
        }
        else if(evt.getKeyCode() == KeyEvent.VK_NUMPAD3 && !answered[1]){
            updateUI(answerButton3.getText(),1);
        }
        if(evt.getKeyCode() == KeyEvent.VK_4 && !answered[0]){
            updateUI(answerButton4.getText(),0);
        }
        else if(evt.getKeyCode() == KeyEvent.VK_NUMPAD4 && !answered[1]){
            updateUI(answerButton4.getText(),1);
        }
    }//GEN-LAST:event_formKeyPressed

/*    
    private void update(String answer,int i){
        boolean flagAnswer = false;
        if(answer.equals(q.getCorrectAnswer()))
            flagAnswer = true;
        game.playerAnswer(flagAnswer, i);
        answered[i] = true;
        ArrayList<Player> pl = game.getPlayers();
        name1.setText(pl.get(0).GetName()+": "+pl.get(0).GetScore());
        if(pl.size()==2){
            name2.setText(pl.get(1).GetName()+": "+pl.get(1).GetScore());
        }
        if(answered[0] &&  answered[1])
            iteration();
    }
*/    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
